"""What a publisher must do, and the pull-request body the kernel writes.

The body is generated by the kernel from the round's own record - never by an
agent - so the same round produces the same text twice and every claim in it
can be checked against the ledger line beside it.

Forge commands run in the operator's environment, not the stripped one an
adapter gets: the kernel is the only writer to the forge, and it needs the
credentials that ``environment.py`` exists to keep away from agents.
"""

from __future__ import annotations

import subprocess
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Mapping, Optional, Sequence, Tuple

from ..errors import InfraError

FORGE_TIMEOUT_S = 300


@dataclass(frozen=True)
class PullRequest:
    url: str
    created: bool


@dataclass(frozen=True)
class Publication:
    """The pull request this round has, or the reason it has none."""

    pull_request: Optional[PullRequest] = None
    reason: str = ""


class Publisher:
    """``name`` is what the config's ``scm`` key selects."""

    name = ""

    def publish(
        self, *, root: Path, branch: str, base: str, title: str, body: str
    ) -> Publication:
        raise NotImplementedError

    def comment(self, root: Path, pull_request: PullRequest, body: str) -> bool:
        """Post one comment.  Whether one is wanted is the ledger's answer, not the forge's."""
        raise NotImplementedError

    def merge(self, root: Path, pull_request: PullRequest) -> str:
        """Squash-merge; the empty string on success, otherwise why not."""
        raise NotImplementedError

    def is_open(self, root: Path, url: str) -> Optional[bool]:
        """Whether the pull request is still open, or None when it cannot be read."""
        raise NotImplementedError


def run(
    argv: Sequence[str],
    cwd: Optional[Path] = None,
    input_text: Optional[str] = None,
    timeout: int = FORGE_TIMEOUT_S,
) -> Tuple[int, str]:
    try:
        completed = subprocess.run(
            list(argv),
            cwd=None if cwd is None else str(cwd),
            input=input_text,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            universal_newlines=True,
            timeout=timeout,
        )
    except (OSError, subprocess.TimeoutExpired) as exc:
        raise InfraError("%s cannot run: %s" % (argv[0], exc))
    return completed.returncode, completed.stdout


def pr_body(
    *,
    item_id: str,
    statement: str,
    worker_reason: str,
    evidence: Mapping[str, Any],
    ledger_line: Mapping[str, Any],
    diff_stat: str,
) -> str:
    """A human-readable explanation of the base...head diff, and its evidence."""
    return "\n".join(
        [
            "## %s" % item_id,
            "",
            statement,
            "",
            "### What this round did",
            "",
            worker_reason or "(the worker recorded no reason)",
            "",
            "### Mutation evidence",
            "",
            "- reverted command: `%s`" % (evidence.get("reverted_command") or "(none)"),
            "- observed failure line: `%s`" % (evidence.get("observed_failure_line") or "(none)"),
            "",
            "### Diff",
            "",
            "```",
            diff_stat.strip() or "(no changes)",
            "```",
            "",
            "### Ledger line",
            "",
            "```",
            "\n".join(
                "%s: %s" % (key, ledger_line.get(key))
                for key in ("ts", "item", "sha", "state", "cost", "duration_s")
            ),
            "```",
            "",
            "Opened by agent-loop. The reviewer's findings follow as one comment.",
        ]
    )


def review_comment(findings: Sequence[Mapping[str, Any]]) -> str:
    """The one comment the reviewer's findings become.

    It carries no marker: invariant 4 keeps loop state off GitHub, and whether a
    review was already posted for this pull request is a question the ledger
    answers.
    """
    lines = ["## Reviewer findings", ""]
    if not findings:
        lines.append("No findings.")
    for finding in findings:
        lines.append(
            "- **%s** at `%s` - %s (cites: %s)"
            % (
                finding.get("kind"),
                finding.get("location"),
                finding.get("claim"),
                finding.get("citation"),
            )
        )
    return "\n".join(lines)
